{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPZlklBiuW7VBfCbCUWqyMy",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/fio1ol/tugas_algoritma_aplikasi_nilai_siswa/blob/main/aplikasi_nilai_data_siswa.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "DUOgIClw9jL7"
      },
      "outputs": [],
      "source": [
        "# Membuat program CLI untuk Manajemen Nilai Siswa\n",
        "# Fitur: tambah data siswa, lihat data, hitung rata-rata, cari nilai tertinggi/terendah, simpan ke file\n",
        "\n",
        "import json\n",
        "\n",
        "# Data disimpan dalam bentuk list of dict\n",
        "data_siswa = []\n",
        "\n",
        "# Fungsi untuk menambahkan siswa\n",
        "def tambah_siswa():\n",
        "    nama = input(\"Masukkan nama siswa: \")\n",
        "    try:\n",
        "        nilai = float(input(\"Masukkan nilai siswa: \"))\n",
        "        data_siswa.append({\"nama\": nama, \"nilai\": nilai})\n",
        "        print(f\"Siswa {nama} dengan nilai {nilai} berhasil ditambahkan!\\n\")\n",
        "    except ValueError:\n",
        "        print(\"Nilai harus berupa angka!\\n\")\n",
        "\n",
        "# Fungsi untuk menampilkan semua data siswa\n",
        "def tampilkan_data():\n",
        "    if not data_siswa:\n",
        "        print(\"Belum ada data siswa.\\n\")\n",
        "        return\n",
        "    print(\"\\nDaftar Nilai Siswa:\")\n",
        "    for i, siswa in enumerate(data_siswa, 1):\n",
        "        print(f\"{i}. {siswa['nama']} - {siswa['nilai']}\")\n",
        "    print()\n",
        "\n",
        "# Fungsi untuk menghitung rata-rata nilai\n",
        "def hitung_rata_rata():\n",
        "    if not data_siswa:\n",
        "        print(\"Data kosong!\\n\")\n",
        "        return\n",
        "    rata2 = sum(s['nilai'] for s in data_siswa) / len(data_siswa)\n",
        "    print(f\"Rata-rata nilai: {rata2:.2f}\\n\")\n",
        "\n",
        "# Fungsi untuk mencari nilai tertinggi\n",
        "def nilai_tertinggi():\n",
        "    if not data_siswa:\n",
        "        print(\"Data kosong!\\n\")\n",
        "        return\n",
        "    max_data = max(data_siswa, key=lambda s: s['nilai'])\n",
        "    print(f\"Nilai tertinggi: {max_data['nama']} - {max_data['nilai']}\\n\")\n",
        "\n",
        "# Fungsi untuk mencari nilai terendah\n",
        "def nilai_terendah():\n",
        "    if not data_siswa:\n",
        "        print(\"Data kosong!\\n\")\n",
        "        return\n",
        "    min_data = min(data_siswa, key=lambda s: s['nilai'])\n",
        "    print(f\"Nilai terendah: {min_data['nama']} - {min_data['nilai']}\\n\")\n",
        "\n",
        "# Fungsi untuk menyimpan data ke file\n",
        "def simpan_ke_file():\n",
        "    with open(\"data_siswa.json\", \"w\") as f:\n",
        "        json.dump(data_siswa, f)\n",
        "    print(\"Data berhasil disimpan ke data_siswa.json\\n\")\n",
        "\n",
        "# Menu utama\n",
        "def menu():\n",
        "    while True:\n",
        "        print(\"=== Aplikasi Manajemen Nilai Siswa ===\")\n",
        "        print(\"1. Tambah Data Siswa\")\n",
        "        print(\"2. Tampilkan Semua Data\")\n",
        "        print(\"3. Hitung Rata-rata\")\n",
        "        print(\"4. Cari Nilai Tertinggi\")\n",
        "        print(\"5. Cari Nilai Terendah\")\n",
        "        print(\"6. Simpan ke File\")\n",
        "        print(\"7. Keluar\")\n",
        "        pilihan = input(\"Pilih menu (1-7): \")\n",
        "\n",
        "        if pilihan == \"1\":\n",
        "            tambah_siswa()\n",
        "        elif pilihan == \"2\":\n",
        "            tampilkan_data()\n",
        "        elif pilihan == \"3\":\n",
        "            hitung_rata_rata()\n",
        "        elif pilihan == \"4\":\n",
        "            nilai_tertinggi()\n",
        "        elif pilihan == \"5\":\n",
        "            nilai_terendah()\n",
        "        elif pilihan == \"6\":\n",
        "            simpan_ke_file()\n",
        "        elif pilihan == \"7\":\n",
        "            print(\"Terima kasih telah menggunakan aplikasi ini!\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Pilihan tidak valid!\\n\")\n",
        "\n",
        "# Jalankan menu saat file ini dieksekusi\n",
        "menu()"
      ]
    }
  ]
}
